apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: opsmgr-data-volume-SIZEg-INST
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: xfs
    pdName: opsmgr-pd-ssd-disk-SIZEg-INST

